# See:
#   https://pre-commit.com
#   https://pre-commit.com/hooks.html
#   https://learn.scientific-python.org/development/guides/style/
# uv run pre-commit install
# uv run pre-commit autoupdate
# uv run pre-commit run --all-files

fail_fast: true

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
    - id: end-of-file-fixer
    - id: trailing-whitespace
    - id: check-merge-conflict
    - id: check-toml

  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.10.4
    hooks:
      - id: uv-lock
        name: uv lock
        files: 'pyproject.toml'

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.1
    hooks:
      - id: ruff-check
        types_or: [python, pyi]
      - id: ruff-format
        types_or: [python, pyi]

  # No official ty pre-commit hook yet (https://github.com/astral-sh/ty/issues/269).
  - repo: local
    hooks:
      - id: ty
        name: ty check
        # entry: .venv/bin/ty check --error-on-warning  # Now in pyproject.toml.
        entry: .venv/bin/ty check
        language: system
        types_or: [python, pyi]

  - repo: https://github.com/DetachHead/basedpyright-pre-commit-mirror
    rev: 1.38.0
    hooks:
      - id: basedpyright
